packages:
  - "frontend"
  - "backend"
virtualStoreDirMaxLength: 120
publicHoistPattern:
  - "*eslint*"
  - "*prettier*"
allowBuilds:
  better-sqlite3: set this to true or false
  core-js: set this to true or false
  esbuild: set this to true or false
  puppeteer: set this to true or false
