/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as SubscriptionsRouteImport } from './routes/subscriptions'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SalaryIncomeRouteImport } from './routes/salary-income'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PeriodsRouteImport } from './routes/periods'
import { Route as PaylaterRouteImport } from './routes/paylater'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as BudgetRouteImport } from './routes/budget'
import { Route as AuditLogRouteImport } from './routes/audit-log'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as IndexRouteImport } from './routes/index'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionsRoute = SubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SalaryIncomeRoute = SalaryIncomeRouteImport.update({
  id: '/salary-income',
  path: '/salary-income',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PeriodsRoute = PeriodsRouteImport.update({
  id: '/periods',
  path: '/periods',
  getParentRoute: () => rootRouteImport,
} as any)
const PaylaterRoute = PaylaterRouteImport.update({
  id: '/paylater',
  path: '/paylater',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const BudgetRoute = BudgetRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditLogRoute = AuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/audit-log': typeof AuditLogRoute
  '/budget': typeof BudgetRoute
  '/categories': typeof CategoriesRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/paylater': typeof PaylaterRoute
  '/periods': typeof PeriodsRoute
  '/reports': typeof ReportsRoute
  '/salary-income': typeof SalaryIncomeRoute
  '/settings': typeof SettingsRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/transactions': typeof TransactionsRoute
  '/wishlist': typeof WishlistRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/audit-log': typeof AuditLogRoute
  '/budget': typeof BudgetRoute
  '/categories': typeof CategoriesRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/paylater': typeof PaylaterRoute
  '/periods': typeof PeriodsRoute
  '/reports': typeof ReportsRoute
  '/salary-income': typeof SalaryIncomeRoute
  '/settings': typeof SettingsRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/transactions': typeof TransactionsRoute
  '/wishlist': typeof WishlistRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/audit-log': typeof AuditLogRoute
  '/budget': typeof BudgetRoute
  '/categories': typeof CategoriesRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/paylater': typeof PaylaterRoute
  '/periods': typeof PeriodsRoute
  '/reports': typeof ReportsRoute
  '/salary-income': typeof SalaryIncomeRoute
  '/settings': typeof SettingsRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/transactions': typeof TransactionsRoute
  '/wishlist': typeof WishlistRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts'
    | '/audit-log'
    | '/budget'
    | '/categories'
    | '/login'
    | '/onboarding'
    | '/paylater'
    | '/periods'
    | '/reports'
    | '/salary-income'
    | '/settings'
    | '/subscriptions'
    | '/transactions'
    | '/wishlist'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounts'
    | '/audit-log'
    | '/budget'
    | '/categories'
    | '/login'
    | '/onboarding'
    | '/paylater'
    | '/periods'
    | '/reports'
    | '/salary-income'
    | '/settings'
    | '/subscriptions'
    | '/transactions'
    | '/wishlist'
  id:
    | '__root__'
    | '/'
    | '/accounts'
    | '/audit-log'
    | '/budget'
    | '/categories'
    | '/login'
    | '/onboarding'
    | '/paylater'
    | '/periods'
    | '/reports'
    | '/salary-income'
    | '/settings'
    | '/subscriptions'
    | '/transactions'
    | '/wishlist'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountsRoute: typeof AccountsRoute
  AuditLogRoute: typeof AuditLogRoute
  BudgetRoute: typeof BudgetRoute
  CategoriesRoute: typeof CategoriesRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PaylaterRoute: typeof PaylaterRoute
  PeriodsRoute: typeof PeriodsRoute
  ReportsRoute: typeof ReportsRoute
  SalaryIncomeRoute: typeof SalaryIncomeRoute
  SettingsRoute: typeof SettingsRoute
  SubscriptionsRoute: typeof SubscriptionsRoute
  TransactionsRoute: typeof TransactionsRoute
  WishlistRoute: typeof WishlistRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscriptions': {
      id: '/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof SubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salary-income': {
      id: '/salary-income'
      path: '/salary-income'
      fullPath: '/salary-income'
      preLoaderRoute: typeof SalaryIncomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/periods': {
      id: '/periods'
      path: '/periods'
      fullPath: '/periods'
      preLoaderRoute: typeof PeriodsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paylater': {
      id: '/paylater'
      path: '/paylater'
      fullPath: '/paylater'
      preLoaderRoute: typeof PaylaterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budget': {
      id: '/budget'
      path: '/budget'
      fullPath: '/budget'
      preLoaderRoute: typeof BudgetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-log': {
      id: '/audit-log'
      path: '/audit-log'
      fullPath: '/audit-log'
      preLoaderRoute: typeof AuditLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountsRoute: AccountsRoute,
  AuditLogRoute: AuditLogRoute,
  BudgetRoute: BudgetRoute,
  CategoriesRoute: CategoriesRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PaylaterRoute: PaylaterRoute,
  PeriodsRoute: PeriodsRoute,
  ReportsRoute: ReportsRoute,
  SalaryIncomeRoute: SalaryIncomeRoute,
  SettingsRoute: SettingsRoute,
  SubscriptionsRoute: SubscriptionsRoute,
  TransactionsRoute: TransactionsRoute,
  WishlistRoute: WishlistRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
